In [105]:
import os
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import seaborn as sns # data visualization
from matplotlib import pyplot as plt
from kaggle_olympic_games_medals import KaggleOlympicGamesMedals

In [106]:
# Instantiate the olympic games medal class
# and load the data
data_dir = '../data/kaggle/olympic-games-medals'
ogm = KaggleOlympicGamesMedals(data_dir)

Data Loaded

In [107]:
# Read the World Bank into new DataFrame
bank_gdp_df = pd.read_csv('../data/World_Bank/World_Bank_GDP_Cleaned.csv', encoding='ISO-8859-1')
bank_food_df = pd.read_csv('../data/World_Bank/Food_Prices_for_Nutrition.csv', encoding='ISO-8859-1')

In [108]:
# Read the Olypic into new DataFrames
olympic_medals_df = pd.read_csv('../data/kaggle/olympic-games-medals/olympic_medals.csv', encoding='ISO-8859-1')
olympic_results_df = pd.read_csv('../data/kaggle/olympic-games-medals/olympic_results.csv', encoding='ISO-8859-1')

In [109]:
bank_gdp_df.columns

Index(['Country Name', 'Country Code', '1960', '1961', '1962', '1963', '1964',
       '1965', '1966', '1967', '1968', '1969', '1970', '1971', '1972', '1973',
       '1974', '1975', '1976', '1977', '1978', '1979', '1980', '1981', '1982',
       '1983', '1984', '1985', '1986', '1987', '1988', '1989', '1990', '1991',
       '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000',
       '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009',
       '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018',
       '2019', '2020', '2021', '2022', '2023', 'Average'],
      dtype='object')

In [110]:
# Get unique GDP values for 'Country_Name'
gdp_unique_country_names = bank_gdp_df['Country Name'].unique()

# Get unique GDP values for 'Country_Code'
gdp_unique_country_codes = bank_gdp_df['Country Code'].unique()

# Convert to lists 
gdp_unique_country_names_list = gdp_unique_country_names.tolist()
gdp_unique_country_codes_list = gdp_unique_country_codes.tolist()

# Print results
print("Unique GDP Country Names:")
print(gdp_unique_country_names_list)

print("\nUnique GDP Country Codes:")
print(gdp_unique_country_codes_list)

Unique GDP Country Names:
['Aruba', 'Africa Eastern and Southern', 'Afghanistan', 'Africa Western and Central', 'Angola', 'Albania', 'Andorra', 'Arab World', 'United Arab Emirates', 'Argentina', 'Armenia', 'American Samoa', 'Antigua and Barbuda', 'Australia', 'Austria', 'Azerbaijan', 'Burundi', 'Belgium', 'Benin', 'Burkina Faso', 'Bangladesh', 'Bulgaria', 'Bahrain', 'Bahamas, The', 'Bosnia and Herzegovina', 'Belarus', 'Belize', 'Bermuda', 'Bolivia', 'Brazil', 'Barbados', 'Brunei Darussalam', 'Bhutan', 'Botswana', 'Central African Republic', 'Canada', 'Central Europe and the Baltics', 'Switzerland', 'Channel Islands', 'Chile', 'China', "Cote d'Ivoire", 'Cameroon', 'Congo, Dem. Rep.', 'Congo, Rep.', 'Colombia', 'Comoros', 'Cabo Verde', 'Costa Rica', 'Caribbean small states', 'Cuba', 'Curacao', 'Cayman Islands', 'Cyprus', 'Czechia', 'Germany', 'Djibouti', 'Dominica', 'Denmark', 'Dominican Republic', 'Algeria', 'East Asia & Pacific (excluding high income)', 'Early-demographic dividend', 'East Asia & Pacific', 'Europe & Central Asia (excluding high income)', 'Europe & Central Asia', 'Ecuador', 'Egypt, Arab Rep.', 'Euro area', 'Eritrea', 'Spain', 'Estonia', 'Ethiopia', 'European Union', 'Fragile and conflict affected situations', 'Finland', 'Fiji', 'France', 'Faroe Islands', 'Micronesia, Fed. Sts.', 'Gabon', 'United Kingdom', 'Georgia', 'Ghana', 'Gibraltar', 'Guinea', 'Gambia, The', 'Guinea-Bissau', 'Equatorial Guinea', 'Greece', 'Grenada', 'Greenland', 'Guatemala', 'Guam', 'Guyana', 'High income', 'Hong Kong SAR, China', 'Honduras', 'Heavily indebted poor countries (HIPC)', 'Croatia', 'Haiti', 'Hungary', 'IBRD only', 'IDA & IBRD total', 'IDA total', 'IDA blend', 'Indonesia', 'IDA only', 'Isle of Man', 'India', 'Not classified', 'Ireland', 'Iran, Islamic Rep.', 'Iraq', 'Iceland', 'Israel', 'Italy', 'Jamaica', 'Jordan', 'Japan', 'Kazakhstan', 'Kenya', 'Kyrgyz Republic', 'Cambodia', 'Kiribati', 'St. Kitts and Nevis', 'Korea, Rep.', 'Kuwait', 'Latin America & Caribbean (excluding high income)', 'Lao PDR', 'Lebanon', 'Liberia', 'Libya', 'St. Lucia', 'Latin America & Caribbean', 'Least developed countries: UN classification', 'Low income', 'Liechtenstein', 'Sri Lanka', 'Lower middle income', 'Low & middle income', 'Lesotho', 'Late-demographic dividend', 'Lithuania', 'Luxembourg', 'Latvia', 'Macao SAR, China', 'St. Martin (French part)', 'Morocco', 'Monaco', 'Moldova', 'Madagascar', 'Maldives', 'Middle East & North Africa', 'Mexico', 'Marshall Islands', 'Middle income', 'North Macedonia', 'Mali', 'Malta', 'Myanmar', 'Middle East & North Africa (excluding high income)', 'Montenegro', 'Mongolia', 'Northern Mariana Islands', 'Mozambique', 'Mauritania', 'Mauritius', 'Malawi', 'Malaysia', 'North America', 'Namibia', 'New Caledonia', 'Niger', 'Nigeria', 'Nicaragua', 'Netherlands', 'Norway', 'Nepal', 'Nauru', 'New Zealand', 'OECD members', 'Oman', 'Other small states', 'Pakistan', 'Panama', 'Peru', 'Philippines', 'Palau', 'Papua New Guinea', 'Poland', 'Pre-demographic dividend', 'Puerto Rico', "Korea, Dem. People's Rep.", 'Portugal', 'Paraguay', 'West Bank and Gaza', 'Pacific island small states', 'Post-demographic dividend', 'French Polynesia', 'Qatar', 'Romania', 'Russian Federation', 'Rwanda', 'South Asia', 'Saudi Arabia', 'Sudan', 'Senegal', 'Singapore', 'Solomon Islands', 'Sierra Leone', 'El Salvador', 'San Marino', 'Somalia', 'Serbia', 'Sub-Saharan Africa (excluding high income)', 'South Sudan', 'Sub-Saharan Africa', 'Small states', 'Sao Tome and Principe', 'Suriname', 'Slovak Republic', 'Slovenia', 'Sweden', 'Eswatini', 'Sint Maarten (Dutch part)', 'Seychelles', 'Syrian Arab Republic', 'Turks and Caicos Islands', 'Chad', 'East Asia & Pacific (IDA & IBRD countries)', 'Europe & Central Asia (IDA & IBRD countries)', 'Togo', 'Thailand', 'Tajikistan', 'Turkmenistan', 'Latin America & the Caribbean (IDA & IBRD countries)', 'Timor-Leste', 'Middle East & North Africa (IDA & IBRD countries)', 'Tonga', 'South Asia (IDA & IBRD)', 'Sub-Saharan Africa (IDA & IBRD countries)', 'Trinidad and Tobago', 'Tunisia', 'Turkiye', 'Tuvalu', 'Tanzania', 'Uganda', 'Ukraine', 'Upper middle income', 'Uruguay', 'United States', 'Uzbekistan', 'St. Vincent and the Grenadines', 'Venezuela, RB', 'British Virgin Islands', 'Virgin Islands (U.S.)', 'Viet Nam', 'Vanuatu', 'World', 'Samoa', 'Kosovo', 'Yemen, Rep.', 'South Africa', 'Zambia', 'Zimbabwe']

Unique GDP Country Codes:
['ABW', 'AFE', 'AFG', 'AFW', 'AGO', 'ALB', 'AND', 'ARB', 'ARE', 'ARG', 'ARM', 'ASM', 'ATG', 'AUS', 'AUT', 'AZE', 'BDI', 'BEL', 'BEN', 'BFA', 'BGD', 'BGR', 'BHR', 'BHS', 'BIH', 'BLR', 'BLZ', 'BMU', 'BOL', 'BRA', 'BRB', 'BRN', 'BTN', 'BWA', 'CAF', 'CAN', 'CEB', 'CHE', 'CHI', 'CHL', 'CHN', 'CIV', 'CMR', 'COD', 'COG', 'COL', 'COM', 'CPV', 'CRI', 'CSS', 'CUB', 'CUW', 'CYM', 'CYP', 'CZE', 'DEU', 'DJI', 'DMA', 'DNK', 'DOM', 'DZA', 'EAP', 'EAR', 'EAS', 'ECA', 'ECS', 'ECU', 'EGY', 'EMU', 'ERI', 'ESP', 'EST', 'ETH', 'EUU', 'FCS', 'FIN', 'FJI', 'FRA', 'FRO', 'FSM', 'GAB', 'GBR', 'GEO', 'GHA', 'GIB', 'GIN', 'GMB', 'GNB', 'GNQ', 'GRC', 'GRD', 'GRL', 'GTM', 'GUM', 'GUY', 'HIC', 'HKG', 'HND', 'HPC', 'HRV', 'HTI', 'HUN', 'IBD', 'IBT', 'IDA', 'IDB', 'IDN', 'IDX', 'IMN', 'IND', 'INX', 'IRL', 'IRN', 'IRQ', 'ISL', 'ISR', 'ITA', 'JAM', 'JOR', 'JPN', 'KAZ', 'KEN', 'KGZ', 'KHM', 'KIR', 'KNA', 'KOR', 'KWT', 'LAC', 'LAO', 'LBN', 'LBR', 'LBY', 'LCA', 'LCN', 'LDC', 'LIC', 'LIE', 'LKA', 'LMC', 'LMY', 'LSO', 'LTE', 'LTU', 'LUX', 'LVA', 'MAC', 'MAF', 'MAR', 'MCO', 'MDA', 'MDG', 'MDV', 'MEA', 'MEX', 'MHL', 'MIC', 'MKD', 'MLI', 'MLT', 'MMR', 'MNA', 'MNE', 'MNG', 'MNP', 'MOZ', 'MRT', 'MUS', 'MWI', 'MYS', 'NAC', 'NAM', 'NCL', 'NER', 'NGA', 'NIC', 'NLD', 'NOR', 'NPL', 'NRU', 'NZL', 'OED', 'OMN', 'OSS', 'PAK', 'PAN', 'PER', 'PHL', 'PLW', 'PNG', 'POL', 'PRE', 'PRI', 'PRK', 'PRT', 'PRY', 'PSE', 'PSS', 'PST', 'PYF', 'QAT', 'ROU', 'RUS', 'RWA', 'SAS', 'SAU', 'SDN', 'SEN', 'SGP', 'SLB', 'SLE', 'SLV', 'SMR', 'SOM', 'SRB', 'SSA', 'SSD', 'SSF', 'SST', 'STP', 'SUR', 'SVK', 'SVN', 'SWE', 'SWZ', 'SXM', 'SYC', 'SYR', 'TCA', 'TCD', 'TEA', 'TEC', 'TGO', 'THA', 'TJK', 'TKM', 'TLA', 'TLS', 'TMN', 'TON', 'TSA', 'TSS', 'TTO', 'TUN', 'TUR', 'TUV', 'TZA', 'UGA', 'UKR', 'UMC', 'URY', 'USA', 'UZB', 'VCT', 'VEN', 'VGB', 'VIR', 'VNM', 'VUT', 'WLD', 'WSM', 'XKX', 'YEM', 'ZAF', 'ZMB', 'ZWE']

In [111]:
gdp_unique_country_names_list.sort()
gdp_unique_country_codes_list.sort()

# Print results
print("Unique GDP Country Names:")
print(gdp_unique_country_names_list)

print("\nUnique GDP Country Codes:")
print(gdp_unique_country_codes_list)

Unique GDP Country Names:
['Afghanistan', 'Africa Eastern and Southern', 'Africa Western and Central', 'Albania', 'Algeria', 'American Samoa', 'Andorra', 'Angola', 'Antigua and Barbuda', 'Arab World', 'Argentina', 'Armenia', 'Aruba', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas, The', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bermuda', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'British Virgin Islands', 'Brunei Darussalam', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cabo Verde', 'Cambodia', 'Cameroon', 'Canada', 'Caribbean small states', 'Cayman Islands', 'Central African Republic', 'Central Europe and the Baltics', 'Chad', 'Channel Islands', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo, Dem. Rep.', 'Congo, Rep.', 'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba', 'Curacao', 'Cyprus', 'Czechia', 'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic', 'Early-demographic dividend', 'East Asia & Pacific', 'East Asia & Pacific (IDA & IBRD countries)', 'East Asia & Pacific (excluding high income)', 'Ecuador', 'Egypt, Arab Rep.', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia', 'Eswatini', 'Ethiopia', 'Euro area', 'Europe & Central Asia', 'Europe & Central Asia (IDA & IBRD countries)', 'Europe & Central Asia (excluding high income)', 'European Union', 'Faroe Islands', 'Fiji', 'Finland', 'Fragile and conflict affected situations', 'France', 'French Polynesia', 'Gabon', 'Gambia, The', 'Georgia', 'Germany', 'Ghana', 'Gibraltar', 'Greece', 'Greenland', 'Grenada', 'Guam', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Heavily indebted poor countries (HIPC)', 'High income', 'Honduras', 'Hong Kong SAR, China', 'Hungary', 'IBRD only', 'IDA & IBRD total', 'IDA blend', 'IDA only', 'IDA total', 'Iceland', 'India', 'Indonesia', 'Iran, Islamic Rep.', 'Iraq', 'Ireland', 'Isle of Man', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', "Korea, Dem. People's Rep.", 'Korea, Rep.', 'Kosovo', 'Kuwait', 'Kyrgyz Republic', 'Lao PDR', 'Late-demographic dividend', 'Latin America & Caribbean', 'Latin America & Caribbean (excluding high income)', 'Latin America & the Caribbean (IDA & IBRD countries)', 'Latvia', 'Least developed countries: UN classification', 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Low & middle income', 'Low income', 'Lower middle income', 'Luxembourg', 'Macao SAR, China', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands', 'Mauritania', 'Mauritius', 'Mexico', 'Micronesia, Fed. Sts.', 'Middle East & North Africa', 'Middle East & North Africa (IDA & IBRD countries)', 'Middle East & North Africa (excluding high income)', 'Middle income', 'Moldova', 'Monaco', 'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nauru', 'Nepal', 'Netherlands', 'New Caledonia', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'North America', 'North Macedonia', 'Northern Mariana Islands', 'Norway', 'Not classified', 'OECD members', 'Oman', 'Other small states', 'Pacific island small states', 'Pakistan', 'Palau', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal', 'Post-demographic dividend', 'Pre-demographic dividend', 'Puerto Rico', 'Qatar', 'Romania', 'Russian Federation', 'Rwanda', 'Samoa', 'San Marino', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Sint Maarten (Dutch part)', 'Slovak Republic', 'Slovenia', 'Small states', 'Solomon Islands', 'Somalia', 'South Africa', 'South Asia', 'South Asia (IDA & IBRD)', 'South Sudan', 'Spain', 'Sri Lanka', 'St. Kitts and Nevis', 'St. Lucia', 'St. Martin (French part)', 'St. Vincent and the Grenadines', 'Sub-Saharan Africa', 'Sub-Saharan Africa (IDA & IBRD countries)', 'Sub-Saharan Africa (excluding high income)', 'Sudan', 'Suriname', 'Sweden', 'Switzerland', 'Syrian Arab Republic', 'Tajikistan', 'Tanzania', 'Thailand', 'Timor-Leste', 'Togo', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkiye', 'Turkmenistan', 'Turks and Caicos Islands', 'Tuvalu', 'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United States', 'Upper middle income', 'Uruguay', 'Uzbekistan', 'Vanuatu', 'Venezuela, RB', 'Viet Nam', 'Virgin Islands (U.S.)', 'West Bank and Gaza', 'World', 'Yemen, Rep.', 'Zambia', 'Zimbabwe']

Unique GDP Country Codes:
['ABW', 'AFE', 'AFG', 'AFW', 'AGO', 'ALB', 'AND', 'ARB', 'ARE', 'ARG', 'ARM', 'ASM', 'ATG', 'AUS', 'AUT', 'AZE', 'BDI', 'BEL', 'BEN', 'BFA', 'BGD', 'BGR', 'BHR', 'BHS', 'BIH', 'BLR', 'BLZ', 'BMU', 'BOL', 'BRA', 'BRB', 'BRN', 'BTN', 'BWA', 'CAF', 'CAN', 'CEB', 'CHE', 'CHI', 'CHL', 'CHN', 'CIV', 'CMR', 'COD', 'COG', 'COL', 'COM', 'CPV', 'CRI', 'CSS', 'CUB', 'CUW', 'CYM', 'CYP', 'CZE', 'DEU', 'DJI', 'DMA', 'DNK', 'DOM', 'DZA', 'EAP', 'EAR', 'EAS', 'ECA', 'ECS', 'ECU', 'EGY', 'EMU', 'ERI', 'ESP', 'EST', 'ETH', 'EUU', 'FCS', 'FIN', 'FJI', 'FRA', 'FRO', 'FSM', 'GAB', 'GBR', 'GEO', 'GHA', 'GIB', 'GIN', 'GMB', 'GNB', 'GNQ', 'GRC', 'GRD', 'GRL', 'GTM', 'GUM', 'GUY', 'HIC', 'HKG', 'HND', 'HPC', 'HRV', 'HTI', 'HUN', 'IBD', 'IBT', 'IDA', 'IDB', 'IDN', 'IDX', 'IMN', 'IND', 'INX', 'IRL', 'IRN', 'IRQ', 'ISL', 'ISR', 'ITA', 'JAM', 'JOR', 'JPN', 'KAZ', 'KEN', 'KGZ', 'KHM', 'KIR', 'KNA', 'KOR', 'KWT', 'LAC', 'LAO', 'LBN', 'LBR', 'LBY', 'LCA', 'LCN', 'LDC', 'LIC', 'LIE', 'LKA', 'LMC', 'LMY', 'LSO', 'LTE', 'LTU', 'LUX', 'LVA', 'MAC', 'MAF', 'MAR', 'MCO', 'MDA', 'MDG', 'MDV', 'MEA', 'MEX', 'MHL', 'MIC', 'MKD', 'MLI', 'MLT', 'MMR', 'MNA', 'MNE', 'MNG', 'MNP', 'MOZ', 'MRT', 'MUS', 'MWI', 'MYS', 'NAC', 'NAM', 'NCL', 'NER', 'NGA', 'NIC', 'NLD', 'NOR', 'NPL', 'NRU', 'NZL', 'OED', 'OMN', 'OSS', 'PAK', 'PAN', 'PER', 'PHL', 'PLW', 'PNG', 'POL', 'PRE', 'PRI', 'PRK', 'PRT', 'PRY', 'PSE', 'PSS', 'PST', 'PYF', 'QAT', 'ROU', 'RUS', 'RWA', 'SAS', 'SAU', 'SDN', 'SEN', 'SGP', 'SLB', 'SLE', 'SLV', 'SMR', 'SOM', 'SRB', 'SSA', 'SSD', 'SSF', 'SST', 'STP', 'SUR', 'SVK', 'SVN', 'SWE', 'SWZ', 'SXM', 'SYC', 'SYR', 'TCA', 'TCD', 'TEA', 'TEC', 'TGO', 'THA', 'TJK', 'TKM', 'TLA', 'TLS', 'TMN', 'TON', 'TSA', 'TSS', 'TTO', 'TUN', 'TUR', 'TUV', 'TZA', 'UGA', 'UKR', 'UMC', 'URY', 'USA', 'UZB', 'VCT', 'VEN', 'VGB', 'VIR', 'VNM', 'VUT', 'WLD', 'WSM', 'XKX', 'YEM', 'ZAF', 'ZMB', 'ZWE']

In [112]:
bank_food_df.columns

Index(['Classification Name', 'Classification Code', 'Country Name',
       'Country Code', 'Time', 'Time Code',
       'Affordability of a healthy diet: ratio of cost to food expenditures [CoHD_fexp]',
       'Affordability of a healthy diet: ratio of cost to the food poverty line [CoHD_pov]',
       'Affordability of a nutrient adequate diet: ratio of cost to food expenditures [CoNA_fexp]',
       'Affordability of a nutrient adequate diet: ratio of cost to the food poverty line [CoNA_pov]',
       'Affordability of an energy sufficient diet: ratio of cost to food expenditures [CoCA_fexp]',
       'Affordability of an energy sufficient diet: ratio of cost to the food poverty line [CoCA_pov]',
       'Cost of a healthy diet [CoHD]',
       'Cost of a healthy diet relative to the cost of sufficient energy from starchy staples [CoHD_CoCA]',
       'Cost of a nutrient adequate diet [CoNA]',
       'Cost of an energy sufficient diet [CoCA]',
       'Cost of animal-source foods [CoHD_asf]',
       'Cost of animal-sourced foods relative to the starchy staples in a least-cost healthy diet [CoHD_asf_ss]',
       'Cost of fruits [CoHD_f]',
       'Cost of fruits relative to the starchy staples in a least-cost healthy diet [CoHD_f_ss]',
       'Cost of legumes, nuts and seeds [CoHD_lns]',
       'Cost of legumes, nuts and seeds relative to the starchy staples in a least-cost healthy diet [CoHD_lns_ss]',
       'Cost of oils and fats [CoHD_of]',
       'Cost of oils and fats relative to the starchy staples in a least-cost healthy diet [CoHD_of_ss]',
       'Cost of starchy staples [CoHD_ss]', 'Cost of vegetables [CoHD_v]',
       'Cost of vegetables relative to the starchy staples in a least-cost healthy diet [CoHD_v_ss]',
       'Cost share for animal-sourced foods in a least-cost healthy diet [CoHD_asf_prop]',
       'Cost share for fruits in a least-cost healthy diet [CoHD_f_prop]',
       'Cost share for legumes, nuts and seeds in a least-cost healthy diet [CoHD_lns_prop]',
       'Cost share for oils and fats in a least-cost healthy diet [CoHD_of_prop]',
       'Cost share for vegetables in a least-cost healthy diet [CoHD_v_prop]',
       'Cost share for starchy staples in a least-cost healthy diet [CoHD_ss_prop]',
       'Percent of the population who cannot afford sufficient calories [CoCA_headcount]',
       'Percent of the population who cannot afford nutrient adequacy [CoNA_headcount]',
       'Percent of the population who cannot afford a healthy diet [CoHD_headcount]',
       'Millions of people who cannot afford sufficient calories [CoCA_unafford_n]',
       'Millions of people who cannot afford nutrient adequacy [CoNA_unafford_n]',
       'Millions of people who cannot afford a healthy diet [CoHD_unafford_n]',
       'Population [Pop]'],
      dtype='object')

In [113]:
bank_food_df.head()

,Classification Name,Classification Code,Country Name,Country Code,Time,Time Code,Affordability of a healthy diet: ratio of cost to food expenditures [CoHD_fexp],Affordability of a healthy diet: ratio of cost to the food poverty line [CoHD_pov],Affordability of a nutrient adequate diet: ratio of cost to food expenditures [CoNA_fexp],Affordability of a nutrient adequate diet: ratio of cost to the food poverty line [CoNA_pov],...,Cost share for oils and fats in a least-cost healthy diet [CoHD_of_prop],Cost share for vegetables in a least-cost healthy diet [CoHD_v_prop],Cost share for starchy staples in a least-cost healthy diet [CoHD_ss_prop],Percent of the population who cannot afford sufficient calories [CoCA_headcount],Percent of the population who cannot afford nutrient adequacy [CoNA_headcount],Percent of the population who cannot afford a healthy diet [CoHD_headcount],Millions of people who cannot afford sufficient calories [CoCA_unafford_n],Millions of people who cannot afford nutrient adequacy [CoNA_unafford_n],Millions of people who cannot afford a healthy diet [CoHD_unafford_n],Population [Pop]
0,Food Prices for Nutrition 1.0,FPN 1.0,Albania,ALB,2017.0,YR2017,0.425,3.992,0.266,2.496,...,0.023,0.179,0.152,0,13,37.8,0,0.4,1.1,2873457
1,Food Prices for Nutrition 1.0,FPN 1.0,Albania,ALB,2018.0,YR2018,..,4.092,..,..,...,..,..,..,..,..,27.9,..,..,0.8,2866376
2,Food Prices for Nutrition 1.0,FPN 1.0,Albania,ALB,2019.0,YR2019,..,4.159,..,..,...,..,..,..,..,..,19.8,..,..,0.6,2854191
3,Food Prices for Nutrition 1.0,FPN 1.0,Albania,ALB,2020.0,YR2020,..,4.239,..,..,...,..,..,..,..,..,20.1,..,..,0.6,2837743
4,Food Prices for Nutrition 1.0,FPN 1.0,Albania,ALB,2021.0,YR2021,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..

In [114]:
# Get unique food values for 'Country_Name'
food_unique_country_names = bank_food_df['Country Name'].unique()

# Get unique food values for 'Country_Code'
food_unique_country_codes = bank_food_df['Country Code'].unique()

# Convert to lists 
food_unique_country_names_list = food_unique_country_names.tolist()
food_unique_country_codes_list = food_unique_country_codes.tolist()

# Print results
print("Unique Food Country Names:")
print(food_unique_country_names_list)

print("\nUnique Food Country Codes:")
print(food_unique_country_codes_list)

Unique Food Country Names:
['Albania', 'Algeria', 'Angola', 'Anguilla', 'Antigua and Barbuda', 'Argentina', 'Armenia', 'Aruba', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas, The', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bermuda', 'Bhutan', 'Bolivia', 'Bonaire', 'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'British Virgin Islands', 'Brunei Darussalam', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cabo Verde', 'Cambodia', 'Cameroon', 'Canada', 'Cayman Islands', 'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo, Dem. Rep.', 'Congo, Rep.', 'Costa Rica', "Côte d'Ivoire", 'Croatia', 'Curacao', 'Cyprus', 'Czech Republic', 'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic', 'East Asia & Pacific', 'Ecuador', 'Egypt, Arab Rep.', 'El Salvador', 'Equatorial Guinea', 'Estonia', 'Eswatini', 'Ethiopia', 'Europe & Central Asia', 'Fiji', 'Finland', 'France', 'Gabon', 'Gambia, The', 'Germany', 'Ghana', 'Greece', 'Grenada', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'High income', 'Honduras', 'Hong Kong SAR, China', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran, Islamic Rep.', 'Iraq', 'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Korea, Rep.', 'Kuwait', 'Kyrgyz Republic', 'Lao PDR', 'Latin America & Caribbean', 'Latvia', 'Lesotho', 'Liberia', 'Lithuania', 'Low income', 'Lower middle income', 'Luxembourg', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Mauritania', 'Mauritius', 'Mexico', 'Middle East & North Africa', 'Moldova', 'Mongolia', 'Montenegro', 'Montserrat', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nepal', 'Netherlands', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'North America', 'North Macedonia', 'Norway', 'Oman', 'Pakistan', 'Panama', 'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal', 'Qatar', 'Romania', 'Russian Federation', 'Rwanda', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Sint Maarten (Dutch part)', 'Slovak Republic', 'Slovenia', 'South Africa', 'South Asia', 'Spain', 'Sri Lanka', 'St. Kitts and Nevis', 'St. Lucia', 'St. Vincent and the Grenadines', 'Sub-Saharan Africa', 'Sudan', 'Suriname', 'Sweden', 'Switzerland', 'Taiwan, China', 'Tajikistan', 'Tanzania', 'Thailand', 'Togo', 'Trinidad and Tobago', 'Tunisia', 'Türkiye', 'Turks and Caicos Islands', 'Uganda', 'United Arab Emirates', 'United Kingdom', 'United States', 'Upper middle income', 'Uruguay', 'Vietnam', 'West Bank and Gaza', 'WORLD', 'Zambia', 'Zimbabwe', nan]

Unique Food Country Codes:
['ALB', 'DZA', 'AGO', 'AIA', 'ATG', 'ARG', 'ARM', 'ABW', 'AUS', 'AUT', 'AZE', 'BHS', 'BHR', 'BGD', 'BRB', 'BLR', 'BEL', 'BLZ', 'BEN', 'BMU', 'BTN', 'BOL', 'BON', 'BIH', 'BWA', 'BRA', 'VGB', 'BRN', 'BGR', 'BFA', 'BDI', 'CPV', 'KHM', 'CMR', 'CAN', 'CYM', 'CAF', 'TCD', 'CHL', 'CHN', 'COL', 'COM', 'COD', 'COG', 'CRI', 'CIV', 'HRV', 'CUW', 'CYP', 'CZE', 'DNK', 'DJI', 'DMA', 'DOM', 'EAS', 'ECU', 'EGY', 'SLV', 'GNQ', 'EST', 'SWZ', 'ETH', 'ECS', 'FJI', 'FIN', 'FRA', 'GAB', 'GMB', 'DEU', 'GHA', 'GRC', 'GRD', 'GIN', 'GNB', 'GUY', 'HTI', 'HIC', 'HND', 'HKG', 'HUN', 'ISL', 'IND', 'IDN', 'IRN', 'IRQ', 'IRL', 'ISR', 'ITA', 'JAM', 'JPN', 'JOR', 'KAZ', 'KEN', 'KOR', 'KWT', 'KGZ', 'LAO', 'LCN', 'LVA', 'LSO', 'LBR', 'LTU', 'LIC', 'LMC', 'LUX', 'MDG', 'MWI', 'MYS', 'MDV', 'MLI', 'MLT', 'MRT', 'MUS', 'MEX', 'MEA', 'MDA', 'MNG', 'MNE', 'MSR', 'MAR', 'MOZ', 'MMR', 'NAM', 'NPL', 'NLD', 'NZL', 'NIC', 'NER', 'NGA', 'NAC', 'MKD', 'NOR', 'OMN', 'PAK', 'PAN', 'PRY', 'PER', 'PHL', 'POL', 'PRT', 'QAT', 'ROU', 'RUS', 'RWA', 'STP', 'SAU', 'SEN', 'SRB', 'SYC', 'SLE', 'SGP', 'SXM', 'SVK', 'SVN', 'ZAF', 'SAS', 'ESP', 'LKA', 'KNA', 'LCA', 'VCT', 'SSF', 'SDN', 'SUR', 'SWE', 'CHE', 'TWN', 'TJK', 'TZA', 'THA', 'TGO', 'TTO', 'TUN', 'TUR', 'TCA', 'UGA', 'ARE', 'GBR', 'USA', 'UMC', 'URY', 'VNM', 'PSE', 'WLD', 'ZMB', 'ZWE', nan]

In [115]:
# Clean the lists: Replace NaN with an empty string and convert to strings
food_unique_country_names_list = [str(x) if pd.notna(x) else '' for x in food_unique_country_names_list]
food_unique_country_codes_list = [str(x) if pd.notna(x) else '' for x in food_unique_country_codes_list]

In [116]:
food_unique_country_names_list.sort()
food_unique_country_codes_list.sort()

# Print results
print("Unique Food Country Names:")
print(food_unique_country_names_list)

print("\nUnique Food Country Codes:")
print(food_unique_country_codes_list)

Unique Food Country Names:
['', 'Albania', 'Algeria', 'Angola', 'Anguilla', 'Antigua and Barbuda', 'Argentina', 'Armenia', 'Aruba', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas, The', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bermuda', 'Bhutan', 'Bolivia', 'Bonaire', 'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'British Virgin Islands', 'Brunei Darussalam', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cabo Verde', 'Cambodia', 'Cameroon', 'Canada', 'Cayman Islands', 'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo, Dem. Rep.', 'Congo, Rep.', 'Costa Rica', 'Croatia', 'Curacao', 'Cyprus', 'Czech Republic', "Côte d'Ivoire", 'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic', 'East Asia & Pacific', 'Ecuador', 'Egypt, Arab Rep.', 'El Salvador', 'Equatorial Guinea', 'Estonia', 'Eswatini', 'Ethiopia', 'Europe & Central Asia', 'Fiji', 'Finland', 'France', 'Gabon', 'Gambia, The', 'Germany', 'Ghana', 'Greece', 'Grenada', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'High income', 'Honduras', 'Hong Kong SAR, China', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran, Islamic Rep.', 'Iraq', 'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Korea, Rep.', 'Kuwait', 'Kyrgyz Republic', 'Lao PDR', 'Latin America & Caribbean', 'Latvia', 'Lesotho', 'Liberia', 'Lithuania', 'Low income', 'Lower middle income', 'Luxembourg', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Mauritania', 'Mauritius', 'Mexico', 'Middle East & North Africa', 'Moldova', 'Mongolia', 'Montenegro', 'Montserrat', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nepal', 'Netherlands', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'North America', 'North Macedonia', 'Norway', 'Oman', 'Pakistan', 'Panama', 'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal', 'Qatar', 'Romania', 'Russian Federation', 'Rwanda', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Sint Maarten (Dutch part)', 'Slovak Republic', 'Slovenia', 'South Africa', 'South Asia', 'Spain', 'Sri Lanka', 'St. Kitts and Nevis', 'St. Lucia', 'St. Vincent and the Grenadines', 'Sub-Saharan Africa', 'Sudan', 'Suriname', 'Sweden', 'Switzerland', 'Taiwan, China', 'Tajikistan', 'Tanzania', 'Thailand', 'Togo', 'Trinidad and Tobago', 'Tunisia', 'Turks and Caicos Islands', 'Türkiye', 'Uganda', 'United Arab Emirates', 'United Kingdom', 'United States', 'Upper middle income', 'Uruguay', 'Vietnam', 'WORLD', 'West Bank and Gaza', 'Zambia', 'Zimbabwe']

Unique Food Country Codes:
['', 'ABW', 'AGO', 'AIA', 'ALB', 'ARE', 'ARG', 'ARM', 'ATG', 'AUS', 'AUT', 'AZE', 'BDI', 'BEL', 'BEN', 'BFA', 'BGD', 'BGR', 'BHR', 'BHS', 'BIH', 'BLR', 'BLZ', 'BMU', 'BOL', 'BON', 'BRA', 'BRB', 'BRN', 'BTN', 'BWA', 'CAF', 'CAN', 'CHE', 'CHL', 'CHN', 'CIV', 'CMR', 'COD', 'COG', 'COL', 'COM', 'CPV', 'CRI', 'CUW', 'CYM', 'CYP', 'CZE', 'DEU', 'DJI', 'DMA', 'DNK', 'DOM', 'DZA', 'EAS', 'ECS', 'ECU', 'EGY', 'ESP', 'EST', 'ETH', 'FIN', 'FJI', 'FRA', 'GAB', 'GBR', 'GHA', 'GIN', 'GMB', 'GNB', 'GNQ', 'GRC', 'GRD', 'GUY', 'HIC', 'HKG', 'HND', 'HRV', 'HTI', 'HUN', 'IDN', 'IND', 'IRL', 'IRN', 'IRQ', 'ISL', 'ISR', 'ITA', 'JAM', 'JOR', 'JPN', 'KAZ', 'KEN', 'KGZ', 'KHM', 'KNA', 'KOR', 'KWT', 'LAO', 'LBR', 'LCA', 'LCN', 'LIC', 'LKA', 'LMC', 'LSO', 'LTU', 'LUX', 'LVA', 'MAR', 'MDA', 'MDG', 'MDV', 'MEA', 'MEX', 'MKD', 'MLI', 'MLT', 'MMR', 'MNE', 'MNG', 'MOZ', 'MRT', 'MSR', 'MUS', 'MWI', 'MYS', 'NAC', 'NAM', 'NER', 'NGA', 'NIC', 'NLD', 'NOR', 'NPL', 'NZL', 'OMN', 'PAK', 'PAN', 'PER', 'PHL', 'POL', 'PRT', 'PRY', 'PSE', 'QAT', 'ROU', 'RUS', 'RWA', 'SAS', 'SAU', 'SDN', 'SEN', 'SGP', 'SLE', 'SLV', 'SRB', 'SSF', 'STP', 'SUR', 'SVK', 'SVN', 'SWE', 'SWZ', 'SXM', 'SYC', 'TCA', 'TCD', 'TGO', 'THA', 'TJK', 'TTO', 'TUN', 'TUR', 'TWN', 'TZA', 'UGA', 'UMC', 'URY', 'USA', 'VCT', 'VGB', 'VNM', 'WLD', 'ZAF', 'ZMB', 'ZWE']

In [117]:
olympic_medals_df.columns

Index(['discipline_title', 'slug_game', 'event_title', 'event_gender',
       'medal_type', 'participant_type', 'participant_title', 'athlete_url',
       'athlete_full_name', 'country_name', 'country_code',
       'country_3_letter_code'],
      dtype='object')

In [118]:
olympic_medals_df.head()

,discipline_title,slug_game,event_title,event_gender,medal_type,participant_type,participant_title,athlete_url,athlete_full_name,country_name,country_code,country_3_letter_code
0,Curling,beijing-2022,Mixed Doubles,Mixed,GOLD,GameTeam,Italy,https://olympics.com/en/athletes/stefania-cons...,Stefania CONSTANTINI,Italy,IT,ITA
1,Curling,beijing-2022,Mixed Doubles,Mixed,GOLD,GameTeam,Italy,https://olympics.com/en/athletes/amos-mosaner,Amos MOSANER,Italy,IT,ITA
2,Curling,beijing-2022,Mixed Doubles,Mixed,SILVER,GameTeam,Norway,https://olympics.com/en/athletes/kristin-skaslien,Kristin SKASLIEN,Norway,NO,NOR
3,Curling,beijing-2022,Mixed Doubles,Mixed,SILVER,GameTeam,Norway,https://olympics.com/en/athletes/magnus-nedreg...,Magnus NEDREGOTTEN,Norway,NO,NOR
4,Curling,beijing-2022,Mixed Doubles,Mixed,BRONZE,GameTeam,Sweden,https://olympics.com/en/athletes/almida-de-val,Almida DE VAL,Sweden,SE,SWE

In [119]:
# Get unique medal values for 'Country_Name'
medals_unique_country_names = olympic_medals_df['country_name'].unique()

# Get unique medal values for 'Country_Code'
medals_unique_country_codes = olympic_medals_df['country_3_letter_code'].unique()

# Convert to lists 
medals_unique_country_names_list = medals_unique_country_names.tolist()
medals_unique_country_codes_list  = medals_unique_country_codes.tolist()

# Print results
print("Unique Medals Country Names:")
print(medals_unique_country_names_list)

print("\nUnique Medals Country Codes:")
print(medals_unique_country_codes_list)

Unique Medals Country Names:
['Italy', 'Norway', 'Sweden', 'Great Britain', 'Japan', 'Canada', 'New Zealand', 'United States of America', 'ROC', 'Switzerland', "People's Republic of China", 'France', 'Australia', 'Germany', 'Ukraine', 'Belarus', 'Estonia', 'Netherlands', 'Hungary', 'Republic of Korea', 'Belgium', 'Spain', 'Slovenia', 'Austria', 'Czech Republic', 'Poland', 'Latvia', 'Finland', 'Slovakia', 'San Marino', 'Serbia', 'Cuba', 'Bulgaria', 'Islamic Republic of Iran', 'Kuwait', 'Denmark', 'Mexico', 'Republic of Moldova', 'Brazil', 'Portugal', 'Ecuador', 'Ireland', 'Philippines', 'Kazakhstan', 'Uzbekistan', 'Azerbaijan', 'Ghana', 'Thailand', 'Turkey', 'India', 'Chinese Taipei', 'Armenia', 'Fiji', 'Argentina', 'Colombia', 'Bermuda', 'South Africa', 'Hong Kong, China', 'Egypt', 'Jordan', 'Croatia', 'North Macedonia', "CÃ´te d'Ivoire", 'Tunisia', 'Israel', 'Malaysia', 'Romania', 'Indonesia', 'Greece', 'Mongolia', 'Kyrgyzstan', 'Nigeria', 'Georgia', 'Venezuela', 'Kosovo', 'Dominican Republic', 'Syrian Arab Republic', 'Turkmenistan', 'Qatar', 'Lithuania', 'Kenya', 'Burkina Faso', 'Uganda', 'Jamaica', 'Ethiopia', 'Bahamas', 'Puerto Rico', 'Bahrain', 'Morocco', 'Namibia', 'Botswana', 'Grenada', 'Saudi Arabia', 'Olympic Athletes from Russia', 'Liechtenstein', 'Russian Federation', 'Vietnam', "Democratic People's Republic of Korea", 'Independent Olympic Athletes', 'Tajikistan', 'Algeria', 'Trinidad and Tobago', 'Burundi', 'United Arab Emirates', 'Niger', 'Singapore', 'Montenegro', 'Cyprus', 'Guatemala', 'Cameroon', 'Gabon', 'Afghanistan', 'Mauritius', 'Iceland', 'Sudan', 'Panama', 'Samoa', 'Chile', 'Zimbabwe', 'Togo', 'Eritrea', 'Paraguay', 'Serbia and Montenegro', 'Uruguay', 'Mozambique', 'Sri Lanka', 'Barbados', 'Costa Rica', 'Zambia', 'Tonga', 'Unified Team', 'Czechoslovakia', 'Pakistan', 'Peru', 'Suriname', 'Luxembourg', 'Federal Republic of Germany', 'Soviet Union', 'German Democratic Republic (Germany)', 'Senegal', 'Djibouti', 'Yugoslavia', 'Netherlands Antilles', 'Virgin Islands, US', 'Lebanon', 'United Republic of Tanzania', 'Guyana', 'West Indies Federation', 'United Arab Republic', 'Iraq', 'Haiti', 'Australasia', 'Bohemia', 'MIX']

Unique Medals Country Codes:
['ITA', 'NOR', 'SWE', 'GBR', 'JPN', 'CAN', 'NZL', 'USA', 'ROC', 'SUI', 'CHN', 'FRA', 'AUS', 'GER', 'UKR', 'BLR', 'EST', 'NED', 'HUN', 'KOR', 'BEL', 'ESP', 'SLO', 'AUT', 'CZE', 'POL', 'LAT', 'FIN', 'SVK', 'SMR', 'SRB', 'CUB', 'BUL', 'IRI', 'KUW', 'DEN', 'MEX', 'MDA', 'BRA', 'POR', 'ECU', 'IRL', 'PHI', 'KAZ', 'UZB', 'AZE', 'GHA', 'THA', 'TUR', 'IND', 'TPE', 'ARM', 'FIJ', 'ARG', 'COL', 'BER', 'RSA', 'HKG', 'EGY', 'JOR', 'CRO', 'MKD', 'CIV', 'TUN', 'ISR', 'MAS', 'ROU', 'INA', 'GRE', 'MGL', 'KGZ', 'NGR', 'GEO', 'VEN', 'KOS', 'DOM', 'SYR', 'TKM', 'QAT', 'LTU', 'KEN', 'BUR', 'UGA', 'JAM', 'ETH', 'BAH', 'PUR', 'BRN', 'MAR', 'NAM', 'BOT', 'GRN', 'KSA', 'OAR', 'LIE', 'RUS', 'VIE', 'PRK', 'IOA', 'TJK', 'ALG', 'TTO', 'BDI', 'UAE', 'NIG', 'SGP', 'MNE', 'CYP', 'GUA', 'CMR', 'GAB', 'AFG', 'MRI', 'ISL', 'SUD', 'PAN', 'SAM', 'CHI', 'ZIM', 'TOG', 'ERI', 'PAR', 'SCG', 'URU', 'MOZ', 'SRI', 'BAR', 'CRC', 'ZAM', 'TGA', 'EUN', 'TCH', 'PAK', 'PER', 'SUR', 'LUX', 'FRG', 'URS', 'GDR', 'SEN', 'DJI', 'YUG', 'AHO', 'ISV', 'LBN', 'TAN', 'GUY', 'WIF', 'UAR', 'IRQ', 'HAI', 'ANZ', 'BOH', 'MIX']

In [120]:
medals_unique_country_names_list.sort()
medals_unique_country_codes_list.sort()

# Print results
print("Unique GDP Country Names:")
print(medals_unique_country_names_list)

print("\nUnique GDP Country Codes:")
print(medals_unique_country_codes_list)

Unique GDP Country Names:
['Afghanistan', 'Algeria', 'Argentina', 'Armenia', 'Australasia', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Barbados', 'Belarus', 'Belgium', 'Bermuda', 'Bohemia', 'Botswana', 'Brazil', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cameroon', 'Canada', 'Chile', 'Chinese Taipei', 'Colombia', 'Costa Rica', 'Croatia', 'Cuba', 'Cyprus', 'Czech Republic', 'Czechoslovakia', "CÃ´te d'Ivoire", "Democratic People's Republic of Korea", 'Denmark', 'Djibouti', 'Dominican Republic', 'Ecuador', 'Egypt', 'Eritrea', 'Estonia', 'Ethiopia', 'Federal Republic of Germany', 'Fiji', 'Finland', 'France', 'Gabon', 'Georgia', 'German Democratic Republic (Germany)', 'Germany', 'Ghana', 'Great Britain', 'Greece', 'Grenada', 'Guatemala', 'Guyana', 'Haiti', 'Hong Kong, China', 'Hungary', 'Iceland', 'Independent Olympic Athletes', 'India', 'Indonesia', 'Iraq', 'Ireland', 'Islamic Republic of Iran', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kosovo', 'Kuwait', 'Kyrgyzstan', 'Latvia', 'Lebanon', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'MIX', 'Malaysia', 'Mauritius', 'Mexico', 'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Namibia', 'Netherlands', 'Netherlands Antilles', 'New Zealand', 'Niger', 'Nigeria', 'North Macedonia', 'Norway', 'Olympic Athletes from Russia', 'Pakistan', 'Panama', 'Paraguay', "People's Republic of China", 'Peru', 'Philippines', 'Poland', 'Portugal', 'Puerto Rico', 'Qatar', 'ROC', 'Republic of Korea', 'Republic of Moldova', 'Romania', 'Russian Federation', 'Samoa', 'San Marino', 'Saudi Arabia', 'Senegal', 'Serbia', 'Serbia and Montenegro', 'Singapore', 'Slovakia', 'Slovenia', 'South Africa', 'Soviet Union', 'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 'Sweden', 'Switzerland', 'Syrian Arab Republic', 'Tajikistan', 'Thailand', 'Togo', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan', 'Uganda', 'Ukraine', 'Unified Team', 'United Arab Emirates', 'United Arab Republic', 'United Republic of Tanzania', 'United States of America', 'Uruguay', 'Uzbekistan', 'Venezuela', 'Vietnam', 'Virgin Islands, US', 'West Indies Federation', 'Yugoslavia', 'Zambia', 'Zimbabwe']

Unique GDP Country Codes:
['AFG', 'AHO', 'ALG', 'ANZ', 'ARG', 'ARM', 'AUS', 'AUT', 'AZE', 'BAH', 'BAR', 'BDI', 'BEL', 'BER', 'BLR', 'BOH', 'BOT', 'BRA', 'BRN', 'BUL', 'BUR', 'CAN', 'CHI', 'CHN', 'CIV', 'CMR', 'COL', 'CRC', 'CRO', 'CUB', 'CYP', 'CZE', 'DEN', 'DJI', 'DOM', 'ECU', 'EGY', 'ERI', 'ESP', 'EST', 'ETH', 'EUN', 'FIJ', 'FIN', 'FRA', 'FRG', 'GAB', 'GBR', 'GDR', 'GEO', 'GER', 'GHA', 'GRE', 'GRN', 'GUA', 'GUY', 'HAI', 'HKG', 'HUN', 'INA', 'IND', 'IOA', 'IRI', 'IRL', 'IRQ', 'ISL', 'ISR', 'ISV', 'ITA', 'JAM', 'JOR', 'JPN', 'KAZ', 'KEN', 'KGZ', 'KOR', 'KOS', 'KSA', 'KUW', 'LAT', 'LBN', 'LIE', 'LTU', 'LUX', 'MAR', 'MAS', 'MDA', 'MEX', 'MGL', 'MIX', 'MKD', 'MNE', 'MOZ', 'MRI', 'NAM', 'NED', 'NGR', 'NIG', 'NOR', 'NZL', 'OAR', 'PAK', 'PAN', 'PAR', 'PER', 'PHI', 'POL', 'POR', 'PRK', 'PUR', 'QAT', 'ROC', 'ROU', 'RSA', 'RUS', 'SAM', 'SCG', 'SEN', 'SGP', 'SLO', 'SMR', 'SRB', 'SRI', 'SUD', 'SUI', 'SUR', 'SVK', 'SWE', 'SYR', 'TAN', 'TCH', 'TGA', 'THA', 'TJK', 'TKM', 'TOG', 'TPE', 'TTO', 'TUN', 'TUR', 'UAE', 'UAR', 'UGA', 'UKR', 'URS', 'URU', 'USA', 'UZB', 'VEN', 'VIE', 'WIF', 'YUG', 'ZAM', 'ZIM']

In [121]:
olympic_results_df.columns

Index(['discipline_title', 'event_title', 'slug_game', 'participant_type',
       'medal_type', 'athletes', 'rank_equal', 'rank_position', 'country_name',
       'country_code', 'country_3_letter_code', 'athlete_url',
       'athlete_full_name', 'value_unit', 'value_type'],
      dtype='object')

In [122]:
# Get unique medal values for 'Country_Name'
results_unique_country_names = olympic_results_df['country_name'].unique()

# Get unique medal values for 'Country_Code'
results_unique_country_codes = olympic_results_df['country_3_letter_code'].unique()

# Convert to lists 
results_unique_country_names_list = results_unique_country_names.tolist()
results_unique_country_codes_list  = results_unique_country_codes.tolist()

# Print results
print("Unique Results Country Names:")
print(results_unique_country_names_list)

print("\nUnique Resultss Country Codes:")
print(results_unique_country_codes_list)

Unique Results Country Names:
['Italy', 'Norway', 'Sweden', 'Great Britain', 'Canada', 'Czech Republic', 'Switzerland', 'United States of America', "People's Republic of China", 'Australia', 'Japan', 'Republic of Korea', 'Denmark', 'ROC', 'Finland', 'Kazakhstan', 'France', 'New Zealand', 'Ireland', 'Austria', 'Spain', 'Germany', 'Estonia', 'Chile', 'Brazil', 'Belarus', 'Ukraine', 'Netherlands', 'Hungary', 'Croatia', 'Poland', 'Belgium', 'Latvia', 'Hong Kong, China', 'Israel', 'Turkey', 'Malta', 'Andorra', 'Slovenia', 'Bulgaria', 'Slovakia', 'Romania', 'Georgia', 'Armenia', 'Lithuania', 'Azerbaijan', 'Mexico', 'Bosnia and Herzegovina', 'Republic of Moldova', 'Argentina', 'Chinese Taipei', 'Puerto Rico', 'Kyrgyzstan', 'Colombia', 'India', 'Portugal', 'San Marino', 'Philippines', 'Lebanon', 'Uzbekistan', 'Albania', 'Montenegro', 'Greece', 'Kosovo', 'Luxembourg', 'Madagascar', 'Cyprus', 'Malaysia', 'Haiti', 'Thailand', 'Pakistan', 'Democratic Republic of Timor-Leste', 'Iceland', 'Monaco', 'Serbia', 'Liechtenstein', 'Bolivia', 'Morocco', 'Ghana', 'Jamaica', 'Eritrea', 'Saudi Arabia', 'Peru', 'Ecuador', 'Islamic Republic of Iran', 'Virgin Islands, US', 'American Samoa', 'Mongolia', 'North Macedonia', 'Nigeria', 'Trinidad and Tobago', 'Egypt', 'Indonesia', 'Cuba', 'Oman', 'Venezuela', 'Bangladesh', 'Afghanistan', 'Singapore', 'Bhutan', 'Algeria', 'Sri Lanka', 'Nepal', 'Refugee Olympic Team', 'Qatar', 'Kuwait', 'Bahrain', 'Senegal', 'Guatemala', 'Iraq', 'Jordan', 'Yemen', 'Tunisia', 'Aruba', 'Myanmar', 'Vietnam', 'Nicaragua', 'United Arab Emirates', 'Dominican Republic', 'South Africa', 'Sao Tome and Principe', 'Samoa', 'Cook Islands', 'Mozambique', 'Belize', 'Ethiopia', 'Costa Rica', 'Paraguay', 'Namibia', 'Rwanda', 'Burkina Faso', 'Panama', 'Zambia', "CÃ´te d'Ivoire", 'Honduras', 'Mauritius', 'Eswatini', 'Uganda', 'Cameroon', 'Democratic Republic of the Congo', 'Tajikistan', 'Kenya', 'Guyana', 'Burundi', 'Botswana', 'Cape Verde', 'Somalia', 'El Salvador', 'Antigua and Barbuda', 'Papua New Guinea', 'Angola', 'Fiji', 'Bermuda', 'Syrian Arab Republic', 'Vanuatu', 'Togo', 'Mali', 'Gabon', 'Niger', 'Tonga', 'Suriname', 'Maldives', 'Guinea-Bissau', 'Guam', 'Guinea', 'Zimbabwe', 'Chad', 'Kiribati', 'Comoros', 'Uruguay', 'Sierra Leone', 'Palestine', 'Sudan', 'Djibouti', 'Gambia', 'Malawi', 'Libya', 'Benin', 'Seychelles', "Lao People's Democratic Republic", 'Turkmenistan', 'Solomon Islands', 'Nauru', 'Virgin Islands, British', 'Lesotho', 'United Republic of Tanzania', 'Liberia', 'Bahamas', 'Dominica', 'Grenada', 'Saint Lucia', 'Olympic Athletes from Russia', "Democratic People's Republic of Korea", 'The Former Yugoslav Republic of Macedonia', 'Korea Team', 'Russian Federation', 'Ivory Coast', 'Independent Olympic Athletes', 'Barbados', 'Cambodia', 'Equatorial Guinea', 'Congo', 'South Sudan', 'Refugee Olympic Athletes', 'Marshall Islands', 'Palau', 'US Virgin Islands', 'Federated States of Micronesia', 'Central African Republic', 'Cayman Islands', 'Brunei', 'Saint Vincent and the Grenadines', 'British Virgin Islands', 'Swaziland', 'Saint Kitts and Nevis', 'Tuvalu', 'Netherlands Antilles', 'Serbia and Montenegro', 'Unified Team', 'Czechoslovakia', 'Mauritania', 'Yugoslavia', 'Soviet Union', 'Federal Republic of Germany', 'German Democratic Republic (Germany)', 'Yemen Arab Republic', 'Yemen Democratic Republic', 'South Vietnam', 'Rhodesia', 'United Arab Republic', 'Malaya', 'West Indies Federation', 'North Borneo', 'Saar', 'MIX', 'Australasia', 'Bohemia', 'Newfoundland']

Unique Resultss Country Codes:
['ITA', 'NOR', 'SWE', 'GBR', 'CAN', 'CZE', 'SUI', 'USA', 'CHN', 'AUS', 'JPN', 'KOR', 'DEN', 'ROC', 'FIN', 'KAZ', 'FRA', 'NZL', 'IRL', 'AUT', 'ESP', 'GER', 'EST', 'CHI', 'BRA', 'BLR', 'UKR', 'NED', 'HUN', 'CRO', 'POL', 'BEL', 'LAT', 'HKG', 'ISR', 'TUR', 'MLT', 'AND', 'SLO', 'BUL', 'SVK', 'ROU', 'GEO', 'ARM', 'LTU', 'AZE', 'MEX', 'BIH', 'MDA', 'ARG', 'TPE', 'PUR', 'KGZ', 'COL', 'IND', 'POR', 'SMR', 'PHI', 'LBN', 'UZB', 'ALB', 'MNE', 'GRE', 'KOS', 'LUX', 'MAD', 'CYP', 'MAS', 'HAI', 'THA', 'PAK', 'TLS', 'ISL', 'MON', 'SRB', 'LIE', 'BOL', 'MAR', 'GHA', 'JAM', 'ERI', 'KSA', 'PER', 'ECU', 'IRI', 'ISV', 'ASA', 'MGL', 'MKD', 'NGR', 'TTO', 'EGY', 'INA', 'CUB', 'OMA', 'VEN', 'BAN', 'AFG', 'SGP', 'BHU', 'ALG', 'SRI', 'NEP', 'EOR', 'QAT', 'KUW', 'BRN', 'SEN', 'GUA', 'IRQ', 'JOR', 'YEM', 'TUN', 'ARU', 'MYA', 'VIE', 'NCA', 'UAE', 'DOM', 'RSA', 'STP', 'SAM', 'COK', 'MOZ', 'BIZ', 'ETH', 'CRC', 'PAR', 'NAM', 'RWA', 'BUR', 'PAN', 'ZAM', 'CIV', 'HON', 'MRI', 'SWZ', 'UGA', 'CMR', 'COD', 'TJK', 'KEN', 'GUY', 'BDI', 'BOT', 'CPV', 'SOM', 'ESA', 'ANT', 'PNG', 'ANG', 'FIJ', 'BER', 'SYR', 'VAN', 'TOG', 'MLI', 'GAB', 'NIG', 'TGA', 'SUR', 'MDV', 'GBS', 'GUM', 'GUI', 'ZIM', 'CHA', 'KIR', 'COM', 'URU', 'SLE', 'PLE', 'SUD', 'DJI', 'GAM', 'MAW', 'LBA', 'BEN', 'SEY', 'LAO', 'TKM', 'SOL', 'NRU', 'IVB', 'LES', 'TAN', 'LBR', 'BAH', 'DMA', 'GRN', 'LCA', 'OAR', 'PRK', 'COR', 'RUS', 'IOA', 'BAR', 'CAM', 'GEQ', 'CGO', 'SSD', 'XXB', 'MHL', 'PLW', 'FSM', 'CAF', 'CAY', 'BRU', 'VIN', 'SKN', 'TUV', 'AHO', 'SCG', 'EUN', 'TCH', 'MTN', 'YUG', 'URS', 'FRG', 'GDR', 'YAR', 'YMD', 'VNM', 'RHO', 'UAR', 'MAL', 'WIF', 'NBO', 'SAA', 'MIX', 'ANZ', 'BOH', 'NFL']

In [123]:
results_unique_country_names_list.sort()
results_unique_country_codes_list.sort()

# Print results
print("Unique GDP Country Names:")
print(results_unique_country_names_list)

print("\nUnique GDP Country Codes:")
print(results_unique_country_codes_list)

Unique GDP Country Names:
['Afghanistan', 'Albania', 'Algeria', 'American Samoa', 'Andorra', 'Angola', 'Antigua and Barbuda', 'Argentina', 'Armenia', 'Aruba', 'Australasia', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bermuda', 'Bhutan', 'Bohemia', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'British Virgin Islands', 'Brunei', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia', 'Cameroon', 'Canada', 'Cape Verde', 'Cayman Islands', 'Central African Republic', 'Chad', 'Chile', 'Chinese Taipei', 'Colombia', 'Comoros', 'Congo', 'Cook Islands', 'Costa Rica', 'Croatia', 'Cuba', 'Cyprus', 'Czech Republic', 'Czechoslovakia', "CÃ´te d'Ivoire", "Democratic People's Republic of Korea", 'Democratic Republic of Timor-Leste', 'Democratic Republic of the Congo', 'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia', 'Eswatini', 'Ethiopia', 'Federal Republic of Germany', 'Federated States of Micronesia', 'Fiji', 'Finland', 'France', 'Gabon', 'Gambia', 'Georgia', 'German Democratic Republic (Germany)', 'Germany', 'Ghana', 'Great Britain', 'Greece', 'Grenada', 'Guam', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras', 'Hong Kong, China', 'Hungary', 'Iceland', 'Independent Olympic Athletes', 'India', 'Indonesia', 'Iraq', 'Ireland', 'Islamic Republic of Iran', 'Israel', 'Italy', 'Ivory Coast', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', 'Korea Team', 'Kosovo', 'Kuwait', 'Kyrgyzstan', "Lao People's Democratic Republic", 'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'MIX', 'Madagascar', 'Malawi', 'Malaya', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands', 'Mauritania', 'Mauritius', 'Mexico', 'Monaco', 'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nauru', 'Nepal', 'Netherlands', 'Netherlands Antilles', 'New Zealand', 'Newfoundland', 'Nicaragua', 'Niger', 'Nigeria', 'North Borneo', 'North Macedonia', 'Norway', 'Olympic Athletes from Russia', 'Oman', 'Pakistan', 'Palau', 'Palestine', 'Panama', 'Papua New Guinea', 'Paraguay', "People's Republic of China", 'Peru', 'Philippines', 'Poland', 'Portugal', 'Puerto Rico', 'Qatar', 'ROC', 'Refugee Olympic Athletes', 'Refugee Olympic Team', 'Republic of Korea', 'Republic of Moldova', 'Rhodesia', 'Romania', 'Russian Federation', 'Rwanda', 'Saar', 'Saint Kitts and Nevis', 'Saint Lucia', 'Saint Vincent and the Grenadines', 'Samoa', 'San Marino', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia', 'Serbia and Montenegro', 'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia', 'Solomon Islands', 'Somalia', 'South Africa', 'South Sudan', 'South Vietnam', 'Soviet Union', 'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 'Swaziland', 'Sweden', 'Switzerland', 'Syrian Arab Republic', 'Tajikistan', 'Thailand', 'The Former Yugoslav Republic of Macedonia', 'Togo', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan', 'Tuvalu', 'US Virgin Islands', 'Uganda', 'Ukraine', 'Unified Team', 'United Arab Emirates', 'United Arab Republic', 'United Republic of Tanzania', 'United States of America', 'Uruguay', 'Uzbekistan', 'Vanuatu', 'Venezuela', 'Vietnam', 'Virgin Islands, British', 'Virgin Islands, US', 'West Indies Federation', 'Yemen', 'Yemen Arab Republic', 'Yemen Democratic Republic', 'Yugoslavia', 'Zambia', 'Zimbabwe']

Unique GDP Country Codes:
['AFG', 'AHO', 'ALB', 'ALG', 'AND', 'ANG', 'ANT', 'ANZ', 'ARG', 'ARM', 'ARU', 'ASA', 'AUS', 'AUT', 'AZE', 'BAH', 'BAN', 'BAR', 'BDI', 'BEL', 'BEN', 'BER', 'BHU', 'BIH', 'BIZ', 'BLR', 'BOH', 'BOL', 'BOT', 'BRA', 'BRN', 'BRU', 'BUL', 'BUR', 'CAF', 'CAM', 'CAN', 'CAY', 'CGO', 'CHA', 'CHI', 'CHN', 'CIV', 'CMR', 'COD', 'COK', 'COL', 'COM', 'COR', 'CPV', 'CRC', 'CRO', 'CUB', 'CYP', 'CZE', 'DEN', 'DJI', 'DMA', 'DOM', 'ECU', 'EGY', 'EOR', 'ERI', 'ESA', 'ESP', 'EST', 'ETH', 'EUN', 'FIJ', 'FIN', 'FRA', 'FRG', 'FSM', 'GAB', 'GAM', 'GBR', 'GBS', 'GDR', 'GEO', 'GEQ', 'GER', 'GHA', 'GRE', 'GRN', 'GUA', 'GUI', 'GUM', 'GUY', 'HAI', 'HKG', 'HON', 'HUN', 'INA', 'IND', 'IOA', 'IRI', 'IRL', 'IRQ', 'ISL', 'ISR', 'ISV', 'ITA', 'IVB', 'JAM', 'JOR', 'JPN', 'KAZ', 'KEN', 'KGZ', 'KIR', 'KOR', 'KOS', 'KSA', 'KUW', 'LAO', 'LAT', 'LBA', 'LBN', 'LBR', 'LCA', 'LES', 'LIE', 'LTU', 'LUX', 'MAD', 'MAL', 'MAR', 'MAS', 'MAW', 'MDA', 'MDV', 'MEX', 'MGL', 'MHL', 'MIX', 'MKD', 'MLI', 'MLT', 'MNE', 'MON', 'MOZ', 'MRI', 'MTN', 'MYA', 'NAM', 'NBO', 'NCA', 'NED', 'NEP', 'NFL', 'NGR', 'NIG', 'NOR', 'NRU', 'NZL', 'OAR', 'OMA', 'PAK', 'PAN', 'PAR', 'PER', 'PHI', 'PLE', 'PLW', 'PNG', 'POL', 'POR', 'PRK', 'PUR', 'QAT', 'RHO', 'ROC', 'ROU', 'RSA', 'RUS', 'RWA', 'SAA', 'SAM', 'SCG', 'SEN', 'SEY', 'SGP', 'SKN', 'SLE', 'SLO', 'SMR', 'SOL', 'SOM', 'SRB', 'SRI', 'SSD', 'STP', 'SUD', 'SUI', 'SUR', 'SVK', 'SWE', 'SWZ', 'SYR', 'TAN', 'TCH', 'TGA', 'THA', 'TJK', 'TKM', 'TLS', 'TOG', 'TPE', 'TTO', 'TUN', 'TUR', 'TUV', 'UAE', 'UAR', 'UGA', 'UKR', 'URS', 'URU', 'USA', 'UZB', 'VAN', 'VEN', 'VIE', 'VIN', 'VNM', 'WIF', 'XXB', 'YAR', 'YEM', 'YMD', 'YUG', 'ZAM', 'ZIM']

In [124]:
# Extract relevant columns from each DataFrame
bank_gdp_selected = bank_gdp_df[['Country Name', 'Country Code'] + [str(year) for year in range(1960, 2024)]]
bank_food_selected = bank_food_df[['Country Name', 'Country Code']]
olympic_medals_selected = olympic_medals_df[['country_name', 'country_3_letter_code', 'medal_type']]
olympic_results_selected = olympic_results_df[['country_name', 'country_3_letter_code', 'medal_type']]

In [125]:
# Reshape bank_gdp_df to have 'Year' as a column and 'GDP' as values
bank_gdp_long = pd.melt(bank_gdp_selected, id_vars=['Country Name', 'Country Code'], var_name='Year', value_name='GDP')
bank_gdp_long['Year'] = bank_gdp_long['Year'].astype(int)  # Ensure 'Year' is integer type

In [126]:
# Create a common 'Year' column for the bank_food_df (assuming each row corresponds to a specific year)
# If 'Time' column represents the year in bank_food_df
bank_food_selected = bank_food_df[['Country Name', 'Country Code', 'Affordability of a healthy diet: ratio of cost to the food poverty line [CoHD_pov]','Time']].rename(columns={'Time': 'Year', 'Affordability of a healthy diet: ratio of cost to the food poverty line [CoHD_pov]': 'Healthy Diet Affordability'})

In [127]:
# Handle non-finite values in 'Year'
bank_food_selected['Year'] = pd.to_numeric(bank_food_selected['Year'], errors='coerce')
bank_food_selected = bank_food_selected.dropna(subset=['Year'])
bank_food_selected['Year'] = bank_food_selected['Year'].astype(int)

In [128]:
# Merging the DataFrames
merged_df = bank_gdp_long.merge(bank_food_selected, on=['Country Name', 'Country Code', 'Year'], how='left')

In [129]:
# ChatGPT assistance for year
# Since olympic_medals_df and olympic_results_df do not contain a year column, 
# assume you want to join them on the country-related columns and medal type.
# This part is tricky as these DataFrames do not directly align with year data.
# If you have a separate logic to associate Olympic data with years, apply it accordingly.

# For simplicity, this example merges based on country and assumes the medal data is for all years combined.
olympic_combined = olympic_medals_selected.merge(olympic_results_selected, 
                                                 on=['country_name', 'country_3_letter_code', 'medal_type'], 
                                                 how='outer')

In [130]:
# Final merge
final_df = merged_df.merge(olympic_combined, 
                           left_on=['Country Name', 'Country Code'], 
                           right_on=['country_name', 'country_3_letter_code'], 
                           how='left')

# Set 'Year' as the index
final_df.set_index('Year', inplace=True)

In [131]:
# Drop duplicate columns from the merge
final_df.drop(columns=['country_name', 'country_3_letter_code'], inplace=True)
# Display the final DataFrame
# print(final_df.head())

In [132]:
final_df

,Country Name,Country Code,GDP,Healthy Diet Affordability,medal_type
Year,,,,,
1960,Aruba,ABW,NaN,NaN,NaN
1960,Africa Eastern and Southern,AFE,21216.96,NaN,NaN
1960,Afghanistan,AFG,NaN,NaN,BRONZE
1960,Afghanistan,AFG,NaN,NaN,BRONZE
1960,Afghanistan,AFG,NaN,NaN,BRONZE
...,...,...,...,...,...
2023,Kosovo,XKX,10438.35,NaN,NaN
2023,"Yemen, Rep.",YEM,NaN,NaN,NaN
2023,South Africa,ZAF,377781.60,NaN,NaN
2023,Zambia,ZMB,28162.63,NaN,NaN
2023,Zimbabwe,ZWE,26538.27,NaN,NaN

In [133]:
final_df.drop_duplicates(inplace=True)

In [134]:
final_df.to_csv('../data/World_Bank/merged_GDP_Food_Medals_data.csv', index=True)
final_df

,Country Name,Country Code,GDP,Healthy Diet Affordability,medal_type
Year,,,,,
1960,Aruba,ABW,NaN,NaN,NaN
1960,Africa Eastern and Southern,AFE,21216.96,NaN,NaN
1960,Afghanistan,AFG,NaN,NaN,BRONZE
1960,Afghanistan,AFG,NaN,NaN,NaN
1960,Africa Western and Central,AFW,11884.13,NaN,NaN
...,...,...,...,...,...
2023,Samoa,WSM,934.10,NaN,NaN
2023,Kosovo,XKX,10438.35,NaN,NaN
2023,South Africa,ZAF,377781.60,NaN,NaN
2023,Zambia,ZMB,28162.63,NaN,NaN
2023,Zimbabwe,ZWE,26538.27,NaN,NaN

In [135]:
# Convert 'GDP' and 'Healthy Diet Affordability' columns to numeric types
final_df['GDP'] = pd.to_numeric(final_df['GDP'], errors='coerce')
final_df['Healthy Diet Affordability'] = pd.to_numeric(final_df['Healthy Diet Affordability'], errors='coerce')

# Calculate mean GDP and Healthy Diet Affordability by country
mean_values = final_df.groupby(['Country Name', 'Country Code']).agg({
    'GDP': 'mean',
    'Healthy Diet Affordability': 'mean'
}).reset_index()

print(mean_values)

                    Country Name Country Code           GDP  \
0                    Afghanistan          AFG  1.309344e+04
1    Africa Eastern and Southern          AFE  3.766765e+05
2     Africa Western and Central          AFW  2.795214e+05
3                        Albania          ALB  9.107035e+03
4                        Algeria          DZA  8.739870e+04
..                           ...          ...           ...
261           West Bank and Gaza          PSE  1.047551e+04
262                        World          WLD  3.356915e+07
263                  Yemen, Rep.          YEM  2.087461e+04
264                       Zambia          ZMB  9.412632e+03
265                     Zimbabwe          ZWE  8.991003e+03

     Healthy Diet Affordability
0                           NaN
1                           NaN
2                           NaN
3                      3.852333
4                      3.602556
..                          ...
261                    3.199111
262                         NaN
263                         NaN
264                    3.060889
265                    2.847000

[266 rows x 4 columns]

In [136]:
# Round GDP and Healthy Diet Affordability to 2 decimal places
mean_values['GDP'] = mean_values['GDP'].round(2)
mean_values['Healthy Diet Affordability'] = mean_values['Healthy Diet Affordability'].round(2)
print(mean_values)

                    Country Name Country Code          GDP  \
0                    Afghanistan          AFG     13093.44
1    Africa Eastern and Southern          AFE    376676.48
2     Africa Western and Central          AFW    279521.42
3                        Albania          ALB      9107.04
4                        Algeria          DZA     87398.70
..                           ...          ...          ...
261           West Bank and Gaza          PSE     10475.51
262                        World          WLD  33569149.06
263                  Yemen, Rep.          YEM     20874.61
264                       Zambia          ZMB      9412.63
265                     Zimbabwe          ZWE      8991.00

     Healthy Diet Affordability
0                           NaN
1                           NaN
2                           NaN
3                          3.85
4                          3.60
..                          ...
261                        3.20
262                         NaN
263                         NaN
264                        3.06
265                        2.85

[266 rows x 4 columns]

In [137]:
mean_values.to_csv('../data/World_Bank/merged_medals_gdp_food.csv')