In [2]:
# Import libraries
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import seaborn as sns # data visualization
from matplotlib import pyplot as plt
from kaggle_olympic_games_medals import KaggleOlympicGamesMedals

In [3]:
# Instantiate the olympic games medal class
# and load the data
data_dir = '../data/kaggle/olympic-games-medals'
ogm = KaggleOlympicGamesMedals(data_dir)

Data Loaded

In [4]:
# Get the medals dataframe with standardized country names
df_medals = ogm.get_medals_by_std_country_name()
df_medals.info()
df_medals

<class 'pandas.core.frame.DataFrame'>
Index: 20124 entries, 0 to 21696
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   discipline_title       20124 non-null  object
 1   slug_game              20124 non-null  object
 2   event_title            20124 non-null  object
 3   event_gender           20124 non-null  object
 4   medal_type             20124 non-null  object
 5   participant_type       20124 non-null  object
 6   country_name           20124 non-null  object
 7   country_3_letter_code  20124 non-null  object
 8   game_end_date          20124 non-null  object
 9   game_start_date        20124 non-null  object
 10  game_location          20124 non-null  object
 11  game_name              20124 non-null  object
 12  game_season            20124 non-null  object
 13  game_year              20124 non-null  int64
dtypes: int64(1), object(13)
memory usage: 2.3+ MB

,discipline_title,slug_game,event_title,event_gender,medal_type,participant_type,country_name,country_3_letter_code,game_end_date,game_start_date,game_location,game_name,game_season,game_year
0,Curling,beijing-2022,mixed doubles,Mixed,GOLD,GameTeam,Italy,ITA,2022-02-20T12:00:00Z,2022-02-04T15:00:00Z,China,Beijing 2022,Winter,2022
2,Curling,beijing-2022,mixed doubles,Mixed,SILVER,GameTeam,Norway,NOR,2022-02-20T12:00:00Z,2022-02-04T15:00:00Z,China,Beijing 2022,Winter,2022
4,Curling,beijing-2022,mixed doubles,Mixed,BRONZE,GameTeam,Sweden,SWE,2022-02-20T12:00:00Z,2022-02-04T15:00:00Z,China,Beijing 2022,Winter,2022
6,Curling,beijing-2022,women,Women,GOLD,GameTeam,Great Britain,GBR,2022-02-20T12:00:00Z,2022-02-04T15:00:00Z,China,Beijing 2022,Winter,2022
7,Curling,beijing-2022,women,Women,SILVER,GameTeam,Japan,JPN,2022-02-20T12:00:00Z,2022-02-04T15:00:00Z,China,Beijing 2022,Winter,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21692,Weightlifting,athens-1896,heavyweight - one hand lift men,Men,SILVER,Athlete,Denmark,DEN,1896-04-15T11:39:39Z,1896-04-06T11:38:39Z,Greece,Athens 1896,Summer,1896
21693,Weightlifting,athens-1896,heavyweight - one hand lift men,Men,BRONZE,Athlete,Greece,GRE,1896-04-15T11:39:39Z,1896-04-06T11:38:39Z,Greece,Athens 1896,Summer,1896
21694,Weightlifting,athens-1896,heavyweight - two hand lift men,Men,GOLD,Athlete,Denmark,DEN,1896-04-15T11:39:39Z,1896-04-06T11:38:39Z,Greece,Athens 1896,Summer,1896
21695,Weightlifting,athens-1896,heavyweight - two hand lift men,Men,SILVER,Athlete,Great Britain,GBR,1896-04-15T11:39:39Z,1896-04-06T11:38:39Z,Greece,Athens 1896,Summer,1896
21696,Weightlifting,athens-1896,heavyweight - two hand lift men,Men,BRONZE,Athlete,Greece,GRE,1896-04-15T11:39:39Z,1896-04-06T11:38:39Z,Greece,Athens 1896,Summer,1896

In [5]:
# Get the count of medals for each country
drop_medal_cols = ['country_3_letter_code', 'game_end_date', 'game_start_date', 'game_location', 'slug_game', 'game_year']
group_medal_cols = ['game_name', 'game_season', 'country_name', 'discipline_title', 'event_title', 'event_gender', 'medal_type']
df_medals_game_season_country = df_medals.drop(columns=drop_medal_cols).groupby(
    group_medal_cols
)['participant_type'].count().reset_index()
df_medals_game_season_country.rename(columns={'participant_type':'medal_count'}, inplace=True)
df_medals_game_season_country.to_csv('../data/etl/medals_by_game_season_country_discip_event_gender_type.csv', index=False)
df_medals_game_season_country.head(10)

,game_name,game_season,country_name,discipline_title,event_title,event_gender,medal_type,medal_count
0,Albertville 1992,Winter,Austria,Alpine Skiing,alpine combined women,Women,GOLD,1
1,Albertville 1992,Winter,Austria,Alpine Skiing,alpine combined women,Women,SILVER,1
2,Albertville 1992,Winter,Austria,Alpine Skiing,downhill men,Men,BRONZE,1
3,Albertville 1992,Winter,Austria,Alpine Skiing,downhill men,Men,GOLD,1
4,Albertville 1992,Winter,Austria,Alpine Skiing,downhill women,Women,BRONZE,1
5,Albertville 1992,Winter,Austria,Alpine Skiing,giant slalom women,Women,SILVER,1
6,Albertville 1992,Winter,Austria,Alpine Skiing,slalom men,Men,BRONZE,1
7,Albertville 1992,Winter,Austria,Alpine Skiing,slalom women,Women,GOLD,1
8,Albertville 1992,Winter,Austria,Bobsleigh,four-man men,Men,GOLD,1
9,Albertville 1992,Winter,Austria,Luge,singles men,Men,BRONZE,1

In [6]:
# Get the medal details dataset
df_medal_details = pd.read_csv('../data/etl/medals_by_game_season_country_discip_event_gender_type.csv')
df_medal_details.head()

,game_name,game_season,country_name,discipline_title,event_title,event_gender,medal_type,medal_count
0,Albertville 1992,Winter,Austria,Alpine Skiing,alpine combined women,Women,GOLD,1
1,Albertville 1992,Winter,Austria,Alpine Skiing,alpine combined women,Women,SILVER,1
2,Albertville 1992,Winter,Austria,Alpine Skiing,downhill men,Men,BRONZE,1
3,Albertville 1992,Winter,Austria,Alpine Skiing,downhill men,Men,GOLD,1
4,Albertville 1992,Winter,Austria,Alpine Skiing,downhill women,Women,BRONZE,1

In [7]:
df_pivot = df_medal_details.pivot(index=['game_name', 'game_season', 'country_name', 'discipline_title', 'event_title', 'event_gender'], columns='medal_type', values='medal_count')
df_pivot

medal_type                                                                                      BRONZE  \
game_name        game_season country_name  discipline_title event_title           event_gender
Albertville 1992 Winter      Austria       Alpine Skiing    alpine combined women Women            NaN
                                                            downhill men          Men              1.0
                                                            downhill women        Women            1.0
                                                            giant slalom women    Women            NaN
                                                            slalom men            Men              1.0
...                                                                                                ...
Vancouver 2010   Winter      United States Snowboard        half-pipe women       Women            1.0
                                                            snowboard cross men   Men              NaN
                                           Speed skating    1000m men             Men              1.0
                                                            1500m men             Men              NaN
                                                            team pursuit men      Men              NaN

medal_type                                                                                      GOLD  \
game_name        game_season country_name  discipline_title event_title           event_gender
Albertville 1992 Winter      Austria       Alpine Skiing    alpine combined women Women          1.0
                                                            downhill men          Men            1.0
                                                            downhill women        Women          NaN
                                                            giant slalom women    Women          NaN
                                                            slalom men            Men            NaN
...                                                                                              ...
Vancouver 2010   Winter      United States Snowboard        half-pipe women       Women          NaN
                                                            snowboard cross men   Men            1.0
                                           Speed skating    1000m men             Men            1.0
                                                            1500m men             Men            NaN
                                                            team pursuit men      Men            NaN

medal_type                                                                                      SILVER
game_name        game_season country_name  discipline_title event_title           event_gender
Albertville 1992 Winter      Austria       Alpine Skiing    alpine combined women Women            1.0
                                                            downhill men          Men              NaN
                                                            downhill women        Women            NaN
                                                            giant slalom women    Women            1.0
                                                            slalom men            Men              NaN
...                                                                                                ...
Vancouver 2010   Winter      United States Snowboard        half-pipe women       Women            1.0
                                                            snowboard cross men   Men              NaN
                                           Speed skating    1000m men             Men              NaN
                                                            1500m men             Men              1.0
                                                            team pursuit men      Men              1.0

[17743 rows x 3 columns]

In [8]:
df_pivot.reset_index(drop=False, inplace=True)
df_pivot = df_pivot.rename(columns={'GOLD': 'gold', 'SILVER': 'silver', 'BRONZE': 'bronze'})
df_pivot = df_pivot[['game_name', 'country_name', 'game_season', 'discipline_title', 'event_title', 'event_gender', 'gold', 'silver', 'bronze']]
df_pivot['total_medals'] = df_pivot[['gold', 'silver', 'bronze']].sum(1)
df_pivot

medal_type,game_name,country_name,game_season,discipline_title,event_title,event_gender,gold,silver,bronze,total_medals
0,Albertville 1992,Austria,Winter,Alpine Skiing,alpine combined women,Women,1.0,1.0,NaN,2.0
1,Albertville 1992,Austria,Winter,Alpine Skiing,downhill men,Men,1.0,NaN,1.0,2.0
2,Albertville 1992,Austria,Winter,Alpine Skiing,downhill women,Women,NaN,NaN,1.0,1.0
3,Albertville 1992,Austria,Winter,Alpine Skiing,giant slalom women,Women,NaN,1.0,NaN,1.0
4,Albertville 1992,Austria,Winter,Alpine Skiing,slalom men,Men,NaN,NaN,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...
17738,Vancouver 2010,United States,Winter,Snowboard,half-pipe women,Women,NaN,1.0,1.0,2.0
17739,Vancouver 2010,United States,Winter,Snowboard,snowboard cross men,Men,1.0,NaN,NaN,1.0
17740,Vancouver 2010,United States,Winter,Speed skating,1000m men,Men,1.0,NaN,1.0,2.0
17741,Vancouver 2010,United States,Winter,Speed skating,1500m men,Men,NaN,1.0,NaN,1.0
17742,Vancouver 2010,United States,Winter,Speed skating,team pursuit men,Men,NaN,1.0,NaN,1.0

In [9]:
# Write to csv
df_pivot.to_csv('../data/etl/medals_by_type_game_country_season_discip_event_gender.csv', index=False)
df_pivot

medal_type,game_name,country_name,game_season,discipline_title,event_title,event_gender,gold,silver,bronze,total_medals
0,Albertville 1992,Austria,Winter,Alpine Skiing,alpine combined women,Women,1.0,1.0,NaN,2.0
1,Albertville 1992,Austria,Winter,Alpine Skiing,downhill men,Men,1.0,NaN,1.0,2.0
2,Albertville 1992,Austria,Winter,Alpine Skiing,downhill women,Women,NaN,NaN,1.0,1.0
3,Albertville 1992,Austria,Winter,Alpine Skiing,giant slalom women,Women,NaN,1.0,NaN,1.0
4,Albertville 1992,Austria,Winter,Alpine Skiing,slalom men,Men,NaN,NaN,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...
17738,Vancouver 2010,United States,Winter,Snowboard,half-pipe women,Women,NaN,1.0,1.0,2.0
17739,Vancouver 2010,United States,Winter,Snowboard,snowboard cross men,Men,1.0,NaN,NaN,1.0
17740,Vancouver 2010,United States,Winter,Speed skating,1000m men,Men,1.0,NaN,1.0,2.0
17741,Vancouver 2010,United States,Winter,Speed skating,1500m men,Men,NaN,1.0,NaN,1.0
17742,Vancouver 2010,United States,Winter,Speed skating,team pursuit men,Men,NaN,1.0,NaN,1.0

In [17]:
# Verify counts
pivot_total_medals = df_pivot.total_medals.sum()
orig_total_medals = df_medals.medal_type.value_counts().sum()
if pivot_total_medals == orig_total_medals:
    print('Pivot total equals original total')
else:
    print('Pivot total does not equal original total')
print('Pivot total:', pivot_total_medals, 'Original total:', orig_total_medals)

Pivot total equals original total
Pivot total: 20124.0 Original total: 20124